# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginIGN
                                 A QGIS plugin
 Plugin para cargar los servicios del IGN / CNIG
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-24
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Alejandro Garcia Barroso
        email                : alejandro.garcia@cnig.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

class Layer:

    def __init__(self,ifaceQgis,iconPath,layerId,layerName,layerUri,menuLayer=None):
        self.iface = ifaceQgis
        self.icon = iconPath
        self.id = layerId
        self.name = layerName
        self.url = layerUri     
        self.menu = menuLayer

        
    def setQmenu(self,qmenu):
        self.menu = qmenu
        
    def setName(self,serviceName):
        self.name = serviceName
        
    def setUrl(self,serviceUrl):
        self.url = serviceUrl 
        
    def addLayerToQgis(self):
        self.iface.addRasterLayer(self.url,self.name,"wms")   
